language: python
python: 
  - "3.6.8"
install:
  - pip install -r requirements.txt
stages:
  - name: dev-test
    if: type = pull_request AND NOT branch = master
  - name: dev-deploy
    if: type = pull_request AND NOT branch = master
  - name: prod-deploy
    if: type = pull_request AND branch = master

jobs:
  include:
    - stage: dev-test
      script:
        - python scripts/test_dev_test.py
    - stage: dev-deploy
      script: 
        - python scripts/test_dev_deploy.py
    - stage: prod-deploy
      script: 
        - python scripts/test_prod_deploy.py
