language: python
python: 
  - "3.6.8"
install:
  - pip install -r requirements.txt
stages:
  - name: dev-test
    if: $TRAVIS_EVENT_TYPE = "pull_request" AND NOT $TRAVIS_PULL_REQUEST_BRANCH = "master"
  - name: dev-deploy
    if: $TRAVIS_EVENT_TYPE = "pull_request" AND NOT $TRAVIS_PULL_REQUEST_BRANCH = "master"
  - name: prod-deploy
    if: $TRAVIS_EVENT_TYPE = "pull_request" AND $TRAVIS_PULL_REQUEST_BRANCH = "master"

jobs:
  include:
    - stage: dev-test
      script:
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_PULL_REQUEST_BRANCH
        - python scripts/test_dev_test.py
    - stage: dev-deploy
      script: 
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_PULL_REQUEST_BRANCH
        - python scripts/test_dev_deploy.py
    - stage: prod-deploy
      script: 
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_PULL_REQUEST_BRANCH
        - python scripts/test_prod_deploy.py
