# Generated by Django 2.1.7 on 2019-08-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('blurb', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('link', models.TextField(blank=True, default='', null=True)),
                ('img', models.FilePathField(blank=True, default='', null=True, path='/img')),
            ],
        ),
    ]
