# Generated by Django 2.2.4 on 2019-08-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_app_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='link',
            new_name='url',
        ),
    ]
