# Generated by Django 2.2.4 on 2019-08-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_auto_20190805_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='author_github',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
