# Generated by Django 2.2.4 on 2019-08-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_app_author_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
