# Generated by Django 2.2.4 on 2019-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0006_auto_20190805_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
